### ISSUE TITLE
Fatal error during file conversion.

### ISSUE THREAD

**Issue by Pactgo24518** [Unfunkable/HoI4-to-Stellaris-Converter#21]
Traceback (most recent call last):
  File "C:\Users\jacks\OneDrive\Documents\space converter\HoI4-to-Stellaris-Converter-eb45bc66fd542760f8baa511d4d48d67a26c2456\Converter.py", line 89, in <module>
    Converter().convert_everything()
    ^^^^^^^^^^^
  File "C:\Users\jacks\OneDrive\Documents\space converter\HoI4-to-Stellaris-Converter-eb45bc66fd542760f8baa511d4d48d67a26c2456\Converter.py", line 16, in __init__
    Config().init()
  File "C:\Users\jacks\OneDrive\Documents\space converter\HoI4-to-Stellaris-Converter-eb45bc66fd542760f8baa511d4d48d67a26c2456\config.py", line 102, in init
    self.parser = naive_parser.Parser(self.savefile)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacks\OneDrive\Documents\space converter\HoI4-to-Stellaris-Converter-eb45bc66fd542760f8baa511d4d48d67a26c2456\naive_parser.py", line 244, in __init__
    self.factories[owner] = int(building)
                            ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '100.000'

**Comment by faris0064** [comment]
Issue is resolved and will be included with the next update.
